In [ ]:
search
----------

In [1]:
import numpy as np


In [3]:
y=np.array([1,2,1,1,1,3,4,5,6])
print(y)

[1 2 1 1 1 3 4 5 6]


In [6]:
z=np.where(y%2==0)
print(z)

(array([1, 6, 8], dtype=int64),)


In [56]:
y=np.array([2,4,7,1,2,1,1,1,3,4,5,6,8,9])
z=np.sort(y)
print(z)
x = np.searchsorted(y,8,side="right")
print(x)

[1 1 1 1 2 2 3 4 4 5 6 7 8 9]
13


In [40]:
y=np.array([1,1,3,4,2,4,5,5,7,5])
x = np.searchsorted(y,4,)
x

5

In [41]:
print(np.searchsorted([1,2,3,4,5], [-10, 10, 2, 3],))

[0 5 1 2]


In [63]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
x=arr>3
y=arr[]
print(y)


2


In [59]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False, True, False, True, False, True, False]
[2 4 6]


In [16]:
y=np.array([1,2,3,1,2,3,4,5])

x = np.searchsorted(y,2)
print(x)

1


In [ ]:
filtering
--------------

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
x=arr>5
print(x)  #result will come false

[False False False False False  True  True]


In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
x=arr[arr>5]
print(x) 

[6 7]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
x=[True,False,True,False,True,False,True]
print(arr[x])

[1 3 5 7]


In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[[True,False,True,False,True,False,True]])

[1 3 5 7]


In [26]:


arr = np.array([1, 2, 3, 4, 5, 6, 7])


filter_arr = []

for element in arr:
    
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

print(filter_arr)

x=arr[filter_arr]
print(x)


[False, True, False, True, False, True, False]
[2 4 6]


In [28]:
x=6
y=[]
for x in range(1,x+1):
    y.append(x)
print(y)

[1, 2, 3, 4, 5, 6]
