In [1]:
import numpy as np 


In [ ]:
conda install numpy(if u get any error then open anaconda prompt and run this code.)

In [4]:
  how to create array? 

In [3]:
import numpy as np 
a=[1,2,3,4]
myarr=np.array(a)
myarr.size

(4,)

In [10]:
# or
import numpy as np
myarr=np.array([1,2,3,4])
myarr


array([1, 2, 3, 4])

In [9]:
# creating array using input command
import numpy as np
a=[]
n=int(input("enter size of the array"))
for i in range(n):
    val=int(input("Enter Number"))
    a.append(val)
myarr=np.array(a)
myarr

enter size of the array5
Enter Number1
Enter Number2
Enter Number3
Enter Number4
Enter Number5


array([1, 2, 3, 4, 5])

In [12]:
import numpy as np
myarr=np.array([[1,2,3,4],[3,4,5,6],[4,5,6,8]])
myarr

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [4, 5, 6, 8]])

In [13]:
import numpy as np 
a=[[1,2,3,4],[3,4,5,6],[4,5,6,8]]
myarr=np.array(a)
myarr

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [4, 5, 6, 8]])

In [16]:
print("dimension of array=",myarr.ndim)
print("dimension of array=",myarr.shape)

dimension of array= 2
dimension of array= (3, 4)


In [ ]:
numpy build in function

In [ ]:
#zeroes

In [11]:
import numpy as np
myarr=np.zeros(15)
print(myarr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
import numpy as np
myarr=np.zeros((2,5))
myarr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
import numpy as np
myarr=np.zeros((4,2,5))
myarr

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
#ones

In [30]:
import numpy as np
myarr=np.ones(3)
myarr

array([1., 1., 1.])

In [31]:
import numpy as np
myarr=np.ones((2,3))
myarr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#eyes
this function creates an array with all the diagonal elements
as 1 and rest 0. in case of a non square matrix the value are still
1 for diagonal(upto which it can draw diagonal)and rest are zero.


In [17]:
import numpy as np
arr=np.eye(3)    #it create 3 by 3 square matrix
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
import numpy as np
arr=np.eye(3,4)  #it create 3 by 4 non square matrix
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
#diag
this function create two dimensional array with all the diagonals elements
as the given value and rest as 0(in a square matrix)

In [2]:
import numpy as np
arr=np.diag([1,2,3,4])  #4 by 4 square with diagonal given values
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [34]:
import numpy as np
arr=np.diag([1,2,3,4])  
print(arr)
np.diag(arr)  #to get diagonal value of any array

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


array([1, 2, 3, 4])

In [ ]:
#randint
this function is used to generate a random number b/w a given range
syntax: randint(min,max,number_of_values)

In [37]:
import numpy as np
arr=np.random.randint(1,10,3)  # b/w 1-9 get 3 random num
arr6

array([4, 9, 5])

In [ ]:
#rand
this function is used to generate a random number b/w 0 to 1
syntax: rand(number_of_values)

In [41]:
import numpy as np
arr=np.random.rand(5) 
arr

array([0.74336114, 0.61856484, 0.32813966, 0.52073886, 0.30941484])

In [42]:
import numpy as np
arr=np.random.rand(2,3)  #it will create 2d array
arr

array([[0.07029182, 0.20794619, 0.16925415],
       [0.07257245, 0.91194525, 0.1745843 ]])

In [ ]:
#randn
this function is used to generate a random number close to 0.it can be -ve or +ve
syntax: rand(number_of_values)

In [5]:
import numpy as np
arr=np.random.randn(5)  
arr

array([ 1.042448  , -1.92396502,  2.53525929,  0.00803404, -1.51483902])

In [ ]:
x=56
