In [1]:
import numpy as np

In [2]:
x=np.array([[1,2,3,4],[4,5,6,7]])
print(x)
print("*"*18)
print(x.transpose())

[[1 2 3 4]
 [4 5 6 7]]
******************
[[1 4]
 [2 5]
 [3 6]
 [4 7]]


In [11]:
x=np.array([[1,2,3,4],[4,5,6,7]])
print(x)
print("*"*18)
print(x.T)

[[1 2 3 4]
 [4 5 6 7]]
******************
[[1 4]
 [2 5]
 [3 6]
 [4 7]]


In [ ]:
mathmatical operation with numpy
****************************************

In [17]:
a1=np.arange(1,10).reshape(3,3)
a2=np.arange(11,20).reshape(3,3)

In [18]:
a1+a2

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [20]:
np.add(a1,a2)

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [21]:
np.subtract(a1,a2)

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [22]:
np.multiply(a1,a2)

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [23]:
np.divide(a1,a2)

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [5]:
a1=np.arange(1,10).reshape(3,3)
a2=np.arange(11,20).reshape(3,3)
print(a1)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [3]:
a1*a2

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [7]:
#matrics product
a1@a2

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [8]:
a1.dot(a2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [28]:
a2.dot(a1)

array([[150, 186, 222],
       [186, 231, 276],
       [222, 276, 330]])

In [9]:
a1.max()

9

In [32]:
#index of max
a1.argmax()

8

In [31]:
a1.min()

1

In [33]:
#index of min
a1.argmin()

0

In [34]:
a1.max(axis=0)

array([7, 8, 9])

In [35]:
a1.max(axis=1)

array([3, 6, 9])

In [37]:
a1.min(axis=0)

array([1, 2, 3])

In [38]:
a1.min(axis=1)

array([1, 4, 7])

In [10]:
# sum of an array
np.sum(a1)


45

In [40]:
np.sum(a1,axis=0)

array([12, 15, 18])

In [41]:
np.sum(a1,axis=1)

array([ 6, 15, 24])

In [11]:
np.mean(a1)

5.0

In [12]:
np.median(a1)

5.0

In [13]:
np.sqrt(a1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [14]:
np.exp(a1)   # e**1, e**2

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [15]:
np.log(a1)   

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [49]:
np.log10(a1)   #log base 10

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [16]:
np.std(a1)   #standard deviation

2.581988897471611

In [51]:
np.std(a1,axis=0) 

array([2.44948974, 2.44948974, 2.44948974])

In [52]:
np.std(a1,axis=1) 

array([0.81649658, 0.81649658, 0.81649658])

In [56]:
np.std(a1,axis=1,dtype=np.float64) #float64 morw accurate

array([0.81649658, 0.81649658, 0.81649658])