In [2]:
import numpy as np

In [9]:
#covert 1d into 2d
x=np.array(range(1,13))
y=x.reshape(2,6)
print(y)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [20]:
#covert 1d into 3d
x=np.array(range(1,13))
y=x.reshape(2,3,2)
print(y)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [13]:
##covert 2d into 1d
x=np.array(range(1,13))
y=x.reshape(2,6)
z=y.reshape(12)
print(z)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [24]:
##covert 2d into 1d using unknow method -1
"""unknown method take one argument tht is -1."""
x=np.array(range(1,13))
y=x.reshape(2,6)
z=y.reshape(-1,)
print(z)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [27]:
#3d to 1 d
x=np.array(range(1,13))
y=x.reshape(2,3,2)
z=y.reshape(-1)
print(z)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [28]:
#3d to 2 d
x=np.array(range(1,13))
y=x.reshape(2,3,2)
z=y.reshape(2,6)
print(z)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [29]:
#3d to 2 d
x=np.array(range(1,13))
y=x.reshape(2,3,2)
z=y.reshape(-1,6)
print(z)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [31]:
#nd to 1 d
x=np.array(range(1,13))
y=x.reshape(2,3,2)
z=y.flatten()
print(z)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [33]:
#nd to 1 d
x=np.array(range(1,13))
y=x.reshape(2,3,2)
z=y.flatten()
print(z)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [34]:
#base method use to get the info of root array 
x=np.array(range(1,13))
y=x.reshape(2,3,2)
z=y.reshape(-1,6)
print(z.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [40]:
x=np.array([[1,2,3],[4,5,6]])
y=x.reshape(-1)
print(y.base)

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
x=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(np.flip(x))

[[[6 5 4]
  [3 2 1]]

 [[6 5 4]
  [3 2 1]]]


In [4]:
A = np.arange(8)
A


# np.flip(A, 0)




# np.flip(A, 1)




# np.flip(A)




# np.flip(A, (0,2))




# A = np.random.randn(3,4,5)
# A
# # np.all(np.flip(A,2) == A[:,:,::-1,...])

array([0, 1, 2, 3, 4, 5, 6, 7])

In [47]:
x=np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])