In [ ]:
https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [3]:
z=np.concatenate((x,y))
print(z)

[1 2 3 4 5 6 7 8]


In [5]:
x=np.array([[1,2,3,4],[11,12,13,14]])
y=np.array([[5,6,7,8],[15,16,17,18]])
print(x)
print(y)

[[ 1  2  3  4]
 [11 12 13 14]]
[[ 5  6  7  8]
 [15 16 17 18]]


In [6]:
z=np.concatenate((x,y),axis=0)
print(z)

[[ 1  2  3  4]
 [11 12 13 14]
 [ 5  6  7  8]
 [15 16 17 18]]


In [7]:
z=np.concatenate((x,y),axis=1)
print(z)

[[ 1  2  3  4  5  6  7  8]
 [11 12 13 14 15 16 17 18]]


In [9]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
z=np.stack((x,y),axis=0)
print(z)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
z=np.hstack((x,y))
print(z)

[1 2 3 4 5 6 7 8]


In [12]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
z=np.vstack((x,y))
print(z)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
z=np.dstack((x,y))
print(z)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [ ]:
spliting
----------

In [20]:
x=np.array([1,2,3,4,6,7,8,5])
z=np.array_split(x,6)
print(z)

[array([1, 2]), array([3, 4]), array([6]), array([7]), array([8]), array([5])]


In [23]:
x=np.array([1,2,3,4,6,7,8,5])  #it will give error if number of elements will not divisible by the given split part
z=np.split(x,3)
print(z)

In [25]:
x=np.array([1,2,3,4,6,7,8,5])
z=np.array_split(x,6)
print(z)
print(z[1])
print(z[2])
print(z[0])

[array([1, 2]), array([3, 4]), array([6]), array([7]), array([8]), array([5])]
[3 4]
[6]
[1 2]
