In [46]:
import numpy as np 
a=[1,2,3,4]
myarr=np.array(a)
# myarr[start:end:step]
print(myarr[-4:-1])

[1 2 3]


In [48]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 80, 9, 10],[6, 78, 8, 9, 10],[6, 87, 8, 9, 10]])
print(arr[-3:-1,-4:-2]) 

[[ 7 80]
 [78  8]]


In [54]:
arr = np.array([[[1, 2, 3, 4, 5], [6, 7, 80, 9, 10]],[[15, 2, 3, 4, 5], [16, 7, 80, 9, 10]]])
print(arr[0,1,2])

80


In [ ]:
data type
__________________________
1) string
2) boolean
3)integer
4)float 
5)complex

In [ ]:
represent the data type
---------------------------
i --> integer
u -->unsigned integer( positive integer)
b --->boolean
S ---> string
c---> complex
f---> float
v--> void
M

In [1]:
import numpy as np 
a=8
myarr=np.array(8)

In [25]:
arr = np.array(["ab", 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'ab' b'2' b'3' b'4']
|S2


In [30]:
import numpy as np

arr = np.array(["abc", "bcg", "cgd","ghh"],dtype="S")

print(arr.dtype) 

|S3


In [32]:
arr=np.datetime64('2005-02-25')
print(arr.dtype) 

datetime64[D]


In [36]:
x=np.array(['2007-07-13', '2006-01-13', '2010-08-13'], dtype='datetime64')
x.dtype


dtype('<M8[D]')

In [37]:
x=np.arange('2005-02', '2005-03', dtype='datetime64[D]')
print(x)

['2005-02-01' '2005-02-02' '2005-02-03' '2005-02-04' '2005-02-05'
 '2005-02-06' '2005-02-07' '2005-02-08' '2005-02-09' '2005-02-10'
 '2005-02-11' '2005-02-12' '2005-02-13' '2005-02-14' '2005-02-15'
 '2005-02-16' '2005-02-17' '2005-02-18' '2005-02-19' '2005-02-20'
 '2005-02-21' '2005-02-22' '2005-02-23' '2005-02-24' '2005-02-25'
 '2005-02-26' '2005-02-27' '2005-02-28']


In [39]:
x=np.datetime64('2009-01-01') - np.datetime64('2007-08-01')
print(x)

519 days


In [40]:
np.is_busday(np.datetime64('2011-07-15'))

True

In [41]:
np.is_busday(np.datetime64('2011-07-16'))

False

In [48]:
np.busday_count(np.datetime64('2020-12-16'), np.datetime64('2020-12-22'))

4

In [54]:
x=np.array([1,0,9,8],dtype=np.bool)

print(x)

[ True False  True  True]


In [56]:
x=np.array([2.33,3.1,2.4])
y=x.astype("i")
print(y)

[2 3 2]


In [58]:
a=[]
x=np.array(a,dtype="V")
print(x.dtype)

|V8


In [60]:
import numpy as np 
a=list(range(1,8))
myarr=np.array(a)
print(myarr)
for i in myarr:
    print(i**2)

[1 2 3 4 5 6 7]
1
4
9
16
25
36
49


In [62]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for i in x:
        print(i)

1
2
3
4
5
6


In [63]:

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [66]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr,flags=["buffered"],op_dtypes="S"):
  print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'


In [73]:
arr = np.array([[1, 2, 3,6,8], [4, 5, 6,10,12]])
for x in np.nditer(arr[:,::3]):
    print(x)

1
6
4
10


In [ ]:
#number to words converter . not a tpoic of numpy

In [74]:
pip install num2words

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\ProgramData\Anaconda3\python.exe -m pip install --upgrade pip' command.


In [6]:
from num2words import num2words
print(num2words(32))

thirty-two


In [7]:
x=int(input("enter the number"))
print(num2words(x))

enter the number764563725
seven hundred and sixty-four million, five hundred and sixty-three thousand, seven hundred and twenty-five


five


4