In [ ]:
what is numpy?
numpy is a python pakage which stands for "Numerical python"
this is created in 2005 by travish oliphant.


In [ ]:
array--> collection of similar type data

In [ ]:
use of numpy:
1. mathmatical and logic calculations on array.
2.using Fourier transforms and routines we can do  shape manipulation
3. it has built in functions for linear algebra, random number generation.
4.used for scientific calculation
5.it is faster than list.
6.it is associated with c prog

In [ ]:
numpy is often called as an alternate of MATLAB(a programing platform designed specifically for engineers and scientis for data analysis.
                                                develloping algoritm create models and applications etc.)

In [ ]:
numpy is used with package like scipy(scientific python) and mat-plotlib(plotting array) and this makes it capable to replace MATLAB.
numpy is dimensional array.
1-d array:
    1,2,3,4  
    it refered to as vactor
2-d array:
    1,2,3,4
    5,5,7,8
       it refered to as matrix
3-d array:
    1,2,3,4
    5,6,7,8
    9,5,7,6
       it refered to as Tensor

In [ ]:
space taken by list and numpy array in bits

In [2]:
import sys

import numpy as np

In [10]:
x=[1,2,3,40,50,30]

y=np.array([1,2,3,40,50,30])

print(x)
print(y)

[1, 2, 3, 40, 50, 30]
[ 1  2  3 40 50 30]


In [11]:
sys.getsizeof(1)*len(x)

168

In [12]:
y.itemsize*y.size

24

In [13]:
x+y−2z=9
−4x+7y+5z=15
3x+4y−12z=35

SyntaxError: invalid character in identifier (<ipython-input-13-7469c422c528>, line 1)

In [14]:
A = np.array([[1, 1, -2], [-4, 7, 5], [3, 4, -12]])
b = np.array([9, 15, 35])
x = np.linalg.solve(A, b)
x

array([ 3.34920635,  4.47619048, -0.58730159])

In [ ]:
4x + 3y + 2z = 25
-2x + 2y + 3z = -10
3x -5y + 2z = -4

In [11]:
A = np.array([[4, 3, 2], [-2, 2, 3], [3, -5, 2]])
B = np.array([25, -10, -4])
X = np.linalg.inv(A).dot(B)

print(X)

[ 5.  3. -2.]
